Sources/HomeForYou/HomeForYou/Areas/back/Controllers/BaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

namespace HomeForYou.Areas.back.Controllers
{
    public class BaoCaoController : Controller
    {
        //
        // GET: /back/BaoCao/
        HelperController helper = new HelperController();
        string role;
        bool is_login;
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }
        // GET: /back/BaoCao/
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("DanhSach");
        }
        public ActionResult BaoCao(string _batdau, string _ketthuc, int? khachsan=0)
        {
            var datacontext = new HomeForYouDataContext();
			ViewBag.pre_batdau = _batdau;
            ViewBag.pre_ketthuc = _ketthuc;
			ViewBag.pre_khachsan = khachsan;
            if (_batdau == null ||_batdau=="") // Xử lý trường hợp không nhập
            {
                _batdau = "01-01-0001";
            }
            if (_ketthuc == null || _ketthuc=="") // Xử lý trường hợp không nhập
            {
                _ketthuc = "01-01-0001";
            }
            DateTime batdau = Convert.ToDateTime(_batdau);
            DateTime ketthuc = Convert.ToDateTime(_ketthuc);
            var ksan = from s in datacontext.KhachSans
                       where s.TinhTrang == "Enabled"
                       select s;
            //ViewData["KhachSan"] = new SelectList(ksan, "MaKS", "TenKS");
            ViewBag.khachsan = ksan;
            if (batdau > ketthuc)
            {
                ViewBag.total_rows = 0;
                ViewBag.FailMessage = "Ngày bắt đầu phải nhỏ hơn ngày kết thúc.";
                return View();
            }
            DateTime tmp;
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
           
            if (batdau == Convert.ToDateTime("01-01-0001"))
            {
                batdau = DateTime.MinValue.Date;
            }
            else
            {
                tmp = (DateTime)batdau;
            }
            if (ketthuc == Convert.ToDateTime("01-01-0001"))
            {
                ketthuc = DateTime.Today;
            }
            if (khachsan == 0)
            {
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return View();
            }
            else
            {
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return View();
            }
            //select ks.TenKS, SUM(hd.TongTien) as DoanhThu
            //from KhachSan ks join Deal d on ks.TenKS = d.KhachSan
            //join ChiTietDatDeal ctd on ctd.MaDeal = d.MaDeal
            //join HoaDon hd on hd.CTDeal = ctd.MaDeal
            //group by ks.TenKS 
        }
		
		[HttpPost]
        public JsonResult layDuLieu()
        {
            HomeForYouDataContext datacontext = new HomeForYouDataContext();
            
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return Json(result);
        }

        [HttpPost]
        public JsonResult layDuLieuMotKhachSan(string _batdau, string _ketthuc, int khachsan)
        {
            HomeForYouDataContext datacontext = new HomeForYouDataContext();
            if (_batdau == null) // Xử lý trường hợp không nhập
            {
                _batdau = "01-01-0001";
            }
            if (_ketthuc == null) // Xử lý trường hợp không nhập
            {
                _ketthuc = "01-01-0001";
            }
            DateTime batdau = Convert.ToDateTime(_batdau);
            DateTime ketthuc = Convert.ToDateTime(_ketthuc);

            int total_rows = 1;
            var result = (from ks in datacontext.KhachSans
                          join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                          join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                          join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                          where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                          group new { ks, d, ctd, hd } by new { thang = System.Convert.ToDateTime(hd.NgayThanhToan).Month.ToString(), nam = System.Convert.ToDateTime(hd.NgayThanhToan).Year.ToString() } into kq
                          select new { thang = (kq.Key.thang + '-' + kq.Key.nam).ToString(), doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
            ViewBag.result = result;
            ViewBag.total_rows = total_rows;
            return Json(result);
        }
    }
}

Sources/HomeForYou/HomeForYou/Areas/back/Controllers/VungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeForYou.Areas.back.Controllers
{
    public class VungController : Controller
    {
        //
     
        HelperController helper = new HelperController();
        string role;
        bool is_login;
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }
        // GET: /back/Vung/
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("DanhSach");
        }

        
        /****** Action thuộc vùng ******/
        public ActionResult DanhSachVung(string title)
        {
            var dataContext = new HomeForYouDataContext();
            if (title != null)
            {
                List<Vung> vung = dataContext.Vungs.Where(v => v.TenVung.Contains(title) == true).ToList();
                return View("DanhSachVung", vung);
            }
            List<Vung> vungs = dataContext.Vungs.ToList();
            // kiem tra delete, edit
            foreach (var d in vungs)
            {
                if (khong_xoa_sua(d.MaVung))
                {
                    d.Xoa = false;
                    d.Sua = false;
                }
            }
            return View("DanhSachVung", vungs);
        }

        public ActionResult ThemVung()
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var thanhpho = from c in dataContext.ThanhPhos
                           where c.TinhTrang == "Enabled"
                           select c;
            ViewData["ThanhPho"] = new SelectList(thanhpho, "MaTP", "TenTP");
            return View();
        }
        [HttpPost]
        public ActionResult ThemVung(string tenvung, int thanhpho)
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var tp = from c in dataContext.ThanhPhos
                     where c.TinhTrang == "Enabled"
                     select c;
            ViewData["ThanhPho"] = new SelectList(tp, "MaTP", "TenTP");
            Vung vung = new Vung();
            if (tenvung == "")
            {
                ViewBag.Message = "Vui lòng nhập đầy đủ thông tin bắt buộc.";
                ViewBag.Success = 0;
                var qg = from c in dataContext.QuocGias
                     where c.TinhTrang == "Enabled"
                     select c;
                ViewData["QuocGia"] = new SelectList(qg, "MaQG", "TenQG");
                return View();
            }
            vung.TenVung = tenvung;
            vung.ThanhPho = thanhpho;
            vung.TinhTrang = "Enabled";
            vung.Xoa = true;
            vung.Sua = true;
            dataContext.Vungs.InsertOnSubmit(vung);
            dataContext.SubmitChanges();
            ViewBag.Message = "Bạn đã thêm vùng" + tenvung + " thành công";
            ViewBag.Success = 1;
            return View();
        }

        [HttpGet]
        public ActionResult SuaVung(int mavung)
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var tp = from c in dataContext.ThanhPhos
                     where c.TinhTrang == "Enabled"
                     select c;
            ViewData["ThanhPho"] = new SelectList(tp, "MaTP", "TenTP");

            var vung = (from s in dataContext.Vungs
                        where s.MaVung == mavung
                        select s).Single();
            return View(vung);
        }

        [HttpPost]
        public ActionResult SuaVung(int mavung, string tenvung, int thanhpho, string tinhtrang)
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var tp = from c in dataContext.ThanhPhos
                     where c.TinhTrang == "Enabled"
                     select c;
            ViewData["ThanhPho"] = new SelectList(tp, "MaTP", "TenTP");
            
            var vung = (from s in dataContext.Vungs
                        where s.MaVung == mavung
                        select s).Single();
            if (tenvung == null || tenvung == "")
            {
                ViewBag.Error = "Vui lòng nhập đầy đủ thông tin bắt buộc!";
                return View(vung);
            }
            vung.TenVung = tenvung;
            vung.ThanhPho = thanhpho;
            vung.TinhTrang = tinhtrang;

            dataContext.SubmitChanges();
            ViewBag.Message = "Bạn cập nhật vùng " + tenvung + " thành công";
            return View(vung);
        }

        public bool khong_xoa_sua(int ID)
        {
            var dataContext = new HomeForYouDataContext();
            var ct = (from c in dataContext.ChiTietDatDeals
                      where c.Deal.KhachSan1.Vung1.MaVung == ID
                      select c).Count();
            if (ct == 0)
            {
                return false;   //cho xoa
            }
            return true;    //khong cho xoa
        }
        
        public void Xoa(int MaVung)
        {
            var dataContext = new HomeForYouDataContext();
            var vung = (from s in dataContext.Vungs
                        where s.MaVung == MaVung
                        select s).Single();
            vung.TinhTrang = "Deleted";
            dataContext.SubmitChanges();
        }
    }
}

Sources/HomeForYou/HomeForYou/Areas/back/Views/Shared/Access_denied.cshtml
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<div class="container" style="padding-top:80px">   
    <div class="row-fluid">
        <div class="span12 well">
            <h1>Bạn không có quyền truy cập vào đường dẫn này.</h1>
            <br/>

            <h4>Nhấn vào @Html.ActionLink("đây", "index", "Admin") để về trang chủ.</h4>
        </div>
    </div>
</div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/Shared/_sidebar_admin.cshtml
<div id="sidebar" class="span3 bs-docs-sidebar">
    <ul class="nav nav-list bs-docs-sidenav well">
        <li class="nav-header"></i>SYSTEM</li>
        <li>@Html.ActionLink("Khách Hàng", "DanhSach", "KhachHang")</li>
        <li>@Html.ActionLink("Nhân Viên", "DanhSach", "NhanVien")</li>
        <li>@Html.ActionLink("Thông tin cá nhân", "ThongTinCaNhan", "NhanVien")</li>
    </ul>
</div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/Shared/_sidebar_manager.cshtml
<div id="sidebar" class="span3 bs-docs-sidebar">
    <ul class="nav nav-list bs-docs-sidenav well">
        <li class="nav-header"></i>Business</li>
        <li>@Html.ActionLink("Nhà cung cấp", "DanhSach", "NhaCungCap")</li>
        <li>@Html.ActionLink("Khách hàng", "DanhSach", "KhachHang")</li>
        <li>@Html.ActionLink("Khách sạn", "xxx", "xxx", new { @class = "thongke" })
		<ul class="thongke-items" style="display: none;">
			<li>@Html.ActionLink("Danh sách", "DanhSach", "KhachSan")</li>
			<li>@Html.ActionLink("Thống kê doanh thu", "ThongKeDoanhThu", "KhachSan")</li>
			<li>@Html.ActionLink("Thống kê đặt deal", "ThongKeLichSuDatDeal", "KhachSan")</li>
		</ul>
        </li>
        <li>@Html.ActionLink("Deal", "DanhSach", "DealKS")</li>
        <li>@Html.ActionLink("Khuyến mãi", "DanhSach", "KhuyenMai")</li>
        <li>@Html.ActionLink("Danh mục", "xxx", "xxx", new { @class = "danhmuc" })
            <ul class="danhmuc-items" style="display: none;">
                <li>@Html.ActionLink("Quốc gia", "DanhSachQuocGia", "QuocGia")</li>
                <li>@Html.ActionLink("Thành phố", "DanhSachThanhPho", "ThanhPho")</li>
                <li>@Html.ActionLink("Vùng", "DanhSachVung", "Vung")</li>
            </ul>
        </li>
        <li>@Html.ActionLink("Báo cáo", "BaoCao", "BaoCao")</li>
        <li>@Html.ActionLink("Thông tin cá nhân", "ThongTinCaNhan", "NhanVien")</li>
    </ul>
</div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/Shared/_sidebar_staff.cshtml
<div id="sidebar" class="span3 bs-docs-sidebar">
    <ul class="nav nav-list bs-docs-sidenav well">
        <li class="nav-header"><i>Tài khoản</i></li>
        <li>@Html.ActionLink("Thông tin cá nhân", "ThongTinCaNhan", "NhanVien")</li>
    </ul>
</div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/Shared/back_layout.cshtml
@{var role = Session["Role"];}

<!DOCTYPE html>
<html>
<head>
     <title>Welcome to Home4You</title>
     <link href="@Url.Content("~/Content/jquery-ui.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/back_style.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.8.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.9.1.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/app.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/tiny_mce/tiny_mce.js")" type="text/javascript" ></script>
    <script type="text/javascript"> tinyMCE.init({ mode: "textareas" }); </script>
    <script  type="text/javascript"  src="https://www.google.com/jsapi"></script>
   @RenderSection("scripts", false);
</head>
<body>
    <header>
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar " data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <div class="brand">@Html.ActionLink("Home For You","Index","Admin")</div>
                    <div class="nav-collapse">
                        <ul class="nav pull-left">
                            <li>@Html.ActionLink("Trang chủ", "Index", "Admin")</li>
                        </ul>
                        <ul class="nav pull-right">
                            <li>@Html.ActionLink("Đổi mật khẩu", "ChangePassword", "Admin")</li>
                            <li>@Html.ActionLink("Thoát", "Logout", "Admin")</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container" style="padding-top: 80px">
        <div class="row">
            @if (role != null)
            {
                @Html.Partial("_sidebar_" + role);
            }
            <div class="span9">
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>