Sources/HomeForYou/HomeForYou/Areas/back/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeForYou.Areas.back.Controllers
{
    public class KhachHangController : Controller
    {
        //
        // GET: /back/KhachHang/
        HelperController helper = new HelperController();
        string role;
        bool is_login;
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }
        [HttpGet]
        public void Index()
        {
            Response.Redirect("List");
        }
        public ActionResult DanhSach(string title)
        {
            // manage role ko quan tam
            /*    if (HttpContext.Session == null || HttpContext.Session["IsLogin"] == null || HttpContext.Session["Role"] == null)
                    return RedirectToAction("Login", "Admin");*/
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam

            var dataContext = new HomeForYouDataContext();
            
            string base_URL = "danhsach"; //quan trong, ten action cua controller

            //phan trang ko quan tam
            int total_rows = (from a in dataContext.KhachHangs
                              select a).Count();
            if (title != null) // dung cho viec search
            {
                total_rows = (from a in dataContext.KhachHangs
                              where a.Ten.Contains(title)
                              select a).Count();
            }
            ViewBag.total_rows = total_rows;
            string URL_segment;
            try
            {
                URL_segment = Request.Url.Segments[4];
            }
            catch (Exception)
            {
                URL_segment = null;
            }
            Libraries.Pagination pagination = new Libraries.Pagination(base_URL, URL_segment, total_rows);
            string pageLinks = pagination.GetPageLinks();
            int start = (pagination.CurPage - 1) * pagination.PerPage;
            int offset = pagination.PerPage;
            if (URL_segment != null)
                pageLinks = pageLinks.Replace(base_URL + "/", "");
            ViewBag.pageLinks = pageLinks;
            //phan trang ko quan tam

            var KhachHangs = (from a in dataContext.KhachHangs
                             select a).Skip(start).Take(offset);
            if (title != null) // dung cho viec search
            {
                KhachHangs = (from a in dataContext.KhachHangs
                             where a.Ten.Contains(title)
                             select a).Skip(start).Take(offset);
            }

            // kiem tra delete, edit
            foreach (var d in KhachHangs)
            {
                if (kietra_xoa_sua(d))
                {
                    d.Xoa = false;
                    d.Sua = false;
                }
            }
            return View(KhachHangs);
        }

        [HttpGet]
        public ActionResult Sua(int ID)
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var khachhang = (from s in dataContext.KhachHangs
                            where s.ID == ID
                            select s).Single();
            return View(khachhang);
        }
        [HttpPost]
        public ActionResult Sua(int ID, string ho, string ten, string diachi, string cmnd, string sodt, string email, string tinhtrang)
        {
            // manage role ko quan tam
            if (HttpContext.Session == null || HttpContext.Session["IsLogin"] == null || HttpContext.Session["Role"] == null)
                return RedirectToAction("Login", "Admin");
            helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role);
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var khachhang = (from s in dataContext.KhachHangs
                            where s.ID == ID
                            select s).Single();
            if (ten=="" || diachi=="" || cmnd==""||email=="")
            {
                ViewBag.Message = "Không để trống các thông tin cần thiết.";
                ViewBag.Success = 0;
                return View(khachhang);
            }
            khachhang.Ho = ho;
            khachhang.Ten = ten;
            khachhang.DiaChi = diachi;
            khachhang.CMND = cmnd;
            khachhang.SoDT = sodt;
            khachhang.Email = email;
            khachhang.TinhTrang = tinhtrang;
            dataContext.SubmitChanges();
            ViewBag.Message = "Bạn cập nhật khách hàng " + ho + ten + " thành công";
            ViewBag.Success = 1;
            return View(khachhang);
        }
        public bool kietra_xoa_sua(KhachHang kh)
        {
            foreach (var c in kh.ChiTietDatDeals)
            {
                if (c.TinhTrang == "Unpaid")
                {
                    return true;
                }
            }
            return false;
        }
      
        public void Xoa(int ID)
        {
            var dataContext = new HomeForYouDataContext();
            var khachhang = (from s in dataContext.KhachHangs
                            where s.ID == ID
                            select s).Single();
                khachhang.TinhTrang = "Deleted";
                dataContext.SubmitChanges();
            //khachhang.TinhTrang = "Deleted";
            //dataContext.SubmitChanges();
        }
        [HttpGet]
        public ActionResult LichSu(int ID, int? tt=null, int? huy=null)
        {
            // manage role
            if (HttpContext.Session == null || HttpContext.Session["IsLogin"] == null || HttpContext.Session["Role"] == null)
                return RedirectToAction("Login", "Admin");
            helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role);
            // manage role 
            var dataContext = new HomeForYouDataContext();

            var khachhang = (from s in dataContext.KhachHangs
                             where s.ID == ID && s.TinhTrang=="Enabled"
                             select s).Single();
            var chitiet = (from s in dataContext.KhachHangs
                           join ct in dataContext.ChiTietDatDeals on s.ID equals ct.MaKH
                           where s.ID == ID
                           select ct);
            ViewBag.ChiTiet = chitiet;
            if (huy == 1)
            {
                ViewBag.Message = "Hủy đặt deal mã số " + ID.ToString() + " thành công";
            }
            if (tt == 1)
            {
                ViewBag.Message = "Thanh toán đặt deal mã số " + ID.ToString() + " thành công";
            }
            return View(khachhang);
        }

        public void Huy(int MaCT, int MaKH)
        {
            var dataContext = new HomeForYouDataContext();
            var chitiet = (from s in dataContext.ChiTietDatDeals
                             where s.MaCT == MaCT
                             select s).Single();
            chitiet.TinhTrang = "Deleted";
            dataContext.SubmitChanges();
            //var t = "LichSu/" + MaKH.ToString();
            var t = "LichSu/" + MaKH.ToString() + "?huy=1";
            Response.Redirect(t);
        }
        public void ThanhToan(int MaCT, int MaKH)
        {
            var dataContext = new HomeForYouDataContext();
            var chitiet = (from s in dataContext.ChiTietDatDeals
                           where s.MaCT == MaCT
                           select s).Single();
            var kh = (from s in dataContext.KhachHangs
                           where s.ID == MaKH
                           select s).Single();
            chitiet.TinhTrang = "Paid";
            kh.TichLuy++;
            dataContext.SubmitChanges();
            var t = "LichSu/" + MaKH.ToString() + "?tt=1"; ;
            Response.Redirect(t);
        }
    }
}

Sources/HomeForYou/HomeForYou/Areas/back/Views/KhachHang/DanhSach.cshtml
@model IEnumerable<HomeForYou.KhachHang>
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách khách hàng", "DanhSach", "KhachHang") <span class="divider"></span>
    </li>
</ul>
<p class="clearfix">
    <div class="pull-left">
        <form class="form-search" method="get">
        <div class="container">
            <input type="hidden" id="controller_name" value="KhachHang" />
        <input type="text" class="input-medium search-query" name="title" placeholder="Từ khóa"
            value="" />
        <button type="submit" class="btn btn-success">
            Tìm</button>
        </form>
         <div class="alert undelete" style="display:none;" >
                <button type="button" class="close" data-dismiss="alert">
                    ×</button>
                <h4>
                    Lỗi!</h4>
                Không thể xóa
            </div>
    </div>
    <table class="table table-bordered table-striped table-center class">
        <thead>
            <tr>
                <th width="30%">
                    Số thẻ KH
                </th>
                <th width="12%">
                    Họ
                </th>
                <th width="12%">
                    Tên
                </th>
                <th width="12%">
                    Địa chỉ
                </th>
                <th width="12%">
                    CMND
                </th>
                <th width="12%">
                    Số ĐT
                </th>
                <th width="12%">
                    Email
                </th>
                <th width="12%">
                    Tình trạng
                </th>
                <th width="10%">
                </th>
                <th width="10%">
                </th>
                <th width="10%">
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@ViewBag.total_rows == 0)
            {
                <tr>
                    <td colspan="5" class="align-center">
                        Không có kết quả phù hợp
                    </td>
                </tr>
            }
            @foreach (var s in Model)
            { 
                <tr>
                    <td style="text-align: center;">
                        <a href="">@s.SoTheKH</a>
                    </td>
                    <td style="text-align: center;">
                        @s.Ho
                    </td>
                    <td style="text-align: center;">
                        @s.Ten
                    </td>
                    <td style="text-align: center;">
                        @s.DiaChi
                    </td>
                    <td style="text-align: center;">
                        @s.CMND
                    </td>
                    <td style="text-align: center;">
                        @s.SoDT
                    </td>
                    <td style="text-align: center;">
                        @s.Email
                    </td>
                    @switch (s.TinhTrang)
                    {
                        case "Disabled":
                        <td>
                            <span class="label btn-warning">Disabled</span>&nbsp;
                        </td>
                            break;
                        case "Deleted":
                        <td>
                            <span class="label btn-danger">Deleted</span>&nbsp;
                        </td>
                            break;
                        default:
                        <td>
                            <span class="label btn-primary">Enabled</span>&nbsp;
                        </td>
                            break;
                    }
                    <td>
                        @if (s.Sua == true)
                        {
                            @Html.ActionLink("Sửa", "Sua", "KhachHang", new { ID = s.ID}, new { @class = "btn btn-small" })
                        }
                        else
                        {
                            <button class="btn btn-small" disabled="disabled">
                                Sửa</button>
                        }
                    </td>
                    <td>
                        @if (s.Xoa == true && s.TinhTrang != "Deleted")
                        {
                            @Html.ActionLink("Xóa", "Xoa", "KhachHang", new { ID = s.ID }, new { @class = "btn btn-small btn-danger delete-row" })
                        }
                        else
                        {
                            <button class="btn btn-small btn-danger delete-row" disabled="disabled">
                                Xóa</button>
                        }
                    </td>
                    <td>
                       @Html.ActionLink("Lịch sử", "LichSu", "KhachHang", new { ID = s.ID }, new { @class = "btn btn-small btn-info" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination clearfix">
        <label>Tổng số dòng: @ViewBag.total_rows
        @if ((string)ViewData["pageLinks"] != "")
        {
            <ul>
                @Html.Raw(ViewBag.pageLinks)
            </ul>
            <br />
            <br />
        }
        </label>
    </div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/KhachHang/LichSu.cshtml
@model HomeForYou.KhachHang
       
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách khách hàng", "DanhSach", "KhachHang") <span class="divider">/</span>
    </li>
    <li class="active">Lịch sử đặt hàng<span class="divider"></span>
    </li>
</ul>
@if (@ViewBag.Message != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Chúc mừng!</h4>
        @ViewBag.Message
    </div>
}
<p class="clearfix">
    <div class="pull-left">
    
        <form class="form-horizontal">
            <div class="control-group">
                <label class="control-label" for="sothe">Số thẻ KH</label>
                <div class="controls">
                    <input type="text" id="sothe" disabled value="@Model.SoTheKH"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="sothe">Họ tên KH</label>
                <div class="controls">
                    <input type="text" id="hoten" disabled value="@Model.Ho @Model.Ten"/>
                </div>
            </div>
        </form>
        <h3 align="center" style="text-align:center; color: blueviolet;">Lịch sử đặt hàng của khách hàng</h3>
    </div>
    <table class="table table-bordered table-striped table-center class">
        <thead>
            <tr>
                <th width="30%">
                    Mã Deal
                </th>
                <th width="12%">
                    Số phòng
                </th>
                <th width="12%">
                    Ngày nhận
                </th>
                <th width="12%">
                    Ngày trả
                </th>
                <th width="12%">
                    Tình trạng
                </th>
                <th width="10%">
                </th>
                <th width="10%">
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@ViewBag.total_rows == 0)
            {
                <tr>
                    <td colspan="5" class="align-center">
                        Không có kết quả phù hợp
                    </td>
                </tr>
            }
            @foreach (var ct in ViewBag.ChiTiet)
            {
                <tr>
                    <td style="text-align: center;">
                        <a href="">@ct.MaDeal</a>
                    </td>
                    <td style="text-align: center;">
                        <a href="">@ct.SoPhong</a>
                    </td>
                    <td style="text-align: center;">
                        <a href="">@ct.NgayNhan</a>
                    </td>
                    <td style="text-align: center;">
                        <a href="">@ct.NgayTra</a>
                    </td>

                    @switch ((string)ct.TinhTrang)
                    {
                        case "Deleted":
                        <td>
                            <span class="label btn-danger">Deleted</span>&nbsp;
                        </td>
                            break;
                        case "Paid":
                        <td>
                            <span class="label btn-primary">Paid</span>&nbsp;
                        </td>
                            break;
                        default:
                        <td>
                            <span class="label btn-primary">Unpaid</span>&nbsp;
                        </td>
                            break;
                    }
                    <td>
                        @if ((string)ct.TinhTrang != "Deleted")
                        {
                          @Html.ActionLink("Hủy", "Huy", "KhachHang", new { MaCT = ct.MaCT, MaKH = ct.KhachHang.ID }, new { @class = "btn btn-small btn-danger" })
                        }
                        @if ((string)ct.TinhTrang == "Deleted")
                        {
                          <input type = "button" disabled value ="Hủy" class = "btn btn-small btn-danger" />
                        }
                    </td>
                    <td>
                        @if ((string)ct.TinhTrang == "Unpaid")
                        {
                            @Html.ActionLink("Thanh toán", "ThanhToan", "KhachHang", new {MaCT = ct.MaCT, MaKH = ct.KhachHang.ID}, new { @class = "btn btn-small btn-info" })
                        }
                        @if ((string)ct.TinhTrang != "Unpaid")
                        {
                            <input type = "button" disabled value ="Thanh toán" class = "btn btn-small btn-info" />
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</p>
    
    <div class="pagination clearfix">
        @if ((string)ViewData["pageLinks"] != "")
        {
            <ul>
                @Html.Raw(ViewBag.pageLinks)
            </ul>
            <br />
            <br />
        }
    </div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/KhachHang/Sua.cshtml
@model HomeForYou.KhachHang
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách khách hàng", "DanhSach", "KhachHang") <span class="divider">/</span>
    </li>
    <li class="active">Cập nhật <span class="divider">/</span> </li>
    <li class="active"></li>
</ul>
<legend>Cập nhật khách hàng: </legend>
@if (@ViewBag.Message != null && ViewBag.Success==1)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Chúc mừng!</h4>
        @ViewBag.Message
    </div>
}
@if (@ViewBag.Message != null && ViewBag.Success==0)
{
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Không thành công!</h4>
        @ViewBag.Message
    </div>
}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
<div class="control-group">
    <div class="controls">
        <input type="hidden" name="ID" value="@Model.ID"/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        SoTheKH</label>
    <div class="controls">
        <input type="text"  disabled value="@Model.SoTheKH"/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Họ</label>
    <div class="controls">
        <input type="text" name="ho" value="@Model.Ho"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Tên</label>
    <div class="controls">
        <input type="text" name="ten" value="@Model.Ten"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Địa chỉ</label>
    <div class="controls">
        <input type="text" name="diachi" value="@Model.DiaChi"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        CMND</label>
    <div class="controls">
        <input type="text" name="cmnd" value="@Model.CMND"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Số ĐT</label>
    <div class="controls">
        <input type="text" name="sodt" value="@Model.SoDT"/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Email</label>
    <div class="controls">
        <input type="text" name="email" value="@Model.Email"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Thẻ tín dụng</label>
    <div class="controls">
        <input type="text"  disabled value="@Model.TheTinDung"/>
    </div>
</div>
<legend>Status</legend>
<div class="control-group">
    <div class="controls">
        <select name="tinhtrang">
            <option value="Enabled"  @if (@Model.TinhTrang == "Enabled") { ViewContext.Writer.Write("selected"); }>
                Enabled</option>
            <option value="Disabled" @if (@Model.TinhTrang == "Disabled") { ViewContext.Writer.Write("selected"); }>
                Disabled</option>
            <option value="Deleted" @if (@Model.TinhTrang == "Deleted") { ViewContext.Writer.Write("selected"); }>
                Deleted</option>
            <option value="other" onclick="TinhTrangKhac">Khác...</option>
        </select>
        <input type="text" value="" name="tinhtrangkhac" style="display: none;"/>
    </div>
</div>
<legend></legend>
<p><strong style="color: Red;"> (*) </strong><strong style="font-style:italic;">: Thông tin không được để trống</strong></p>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">
        Cập nhật</button>
    @Html.ActionLink("Thoát", "DanhSach", "KhachHang", new { @class = "btn btn-inverse" })
</div>
</form>