Sources/HomeForYou/HomeForYou/Areas/back/Controllers/BaoCaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;

namespace HomeForYou.Areas.back.Controllers
{
    public class BaoCaoController : Controller
    {
        //
        // GET: /back/BaoCao/
        HelperController helper = new HelperController();
        string role;
        bool is_login;
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }
        // GET: /back/BaoCao/
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("DanhSach");
        }
        public ActionResult BaoCao(string _batdau, string _ketthuc, int? khachsan=0)
        {
            var datacontext = new HomeForYouDataContext();
			ViewBag.pre_batdau = _batdau;
            ViewBag.pre_ketthuc = _ketthuc;
			ViewBag.pre_khachsan = khachsan;
            if (_batdau == null ||_batdau=="") // Xử lý trường hợp không nhập
            {
                _batdau = "01-01-0001";
            }
            if (_ketthuc == null || _ketthuc=="") // Xử lý trường hợp không nhập
            {
                _ketthuc = "01-01-0001";
            }
            DateTime batdau = Convert.ToDateTime(_batdau);
            DateTime ketthuc = Convert.ToDateTime(_ketthuc);
            var ksan = from s in datacontext.KhachSans
                       where s.TinhTrang == "Enabled"
                       select s;
            //ViewData["KhachSan"] = new SelectList(ksan, "MaKS", "TenKS");
            ViewBag.khachsan = ksan;
            if (batdau > ketthuc)
            {
                ViewBag.total_rows = 0;
                ViewBag.FailMessage = "Ngày bắt đầu phải nhỏ hơn ngày kết thúc.";
                return View();
            }
            DateTime tmp;
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
           
            if (batdau == Convert.ToDateTime("01-01-0001"))
            {
                batdau = DateTime.MinValue.Date;
            }
            else
            {
                tmp = (DateTime)batdau;
            }
            if (ketthuc == Convert.ToDateTime("01-01-0001"))
            {
                ketthuc = DateTime.Today;
            }
            if (khachsan == 0)
            {
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return View();
            }
            else
            {
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return View();
            }
            //select ks.TenKS, SUM(hd.TongTien) as DoanhThu
            //from KhachSan ks join Deal d on ks.TenKS = d.KhachSan
            //join ChiTietDatDeal ctd on ctd.MaDeal = d.MaDeal
            //join HoaDon hd on hd.CTDeal = ctd.MaDeal
            //group by ks.TenKS 
        }
		
		[HttpPost]
        public JsonResult layDuLieu()
        {
            HomeForYouDataContext datacontext = new HomeForYouDataContext();
            
                int total_rows = (from ks in datacontext.KhachSans
                                  join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                                  join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                                  join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                                  group new { ks, d, ctd, hd } by ks.TenKS into kq
                                  select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).Count();
                var result = (from ks in datacontext.KhachSans
                              join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                              join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                              join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                              group new { ks, d, ctd, hd } by ks.TenKS into kq
                              select new DoanhThu { tenks = kq.Key, doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
                ViewBag.result = result;
                ViewBag.total_rows = total_rows;
                return Json(result);
        }

        [HttpPost]
        public JsonResult layDuLieuMotKhachSan(string _batdau, string _ketthuc, int khachsan)
        {
            HomeForYouDataContext datacontext = new HomeForYouDataContext();
            if (_batdau == null) // Xử lý trường hợp không nhập
            {
                _batdau = "01-01-0001";
            }
            if (_ketthuc == null) // Xử lý trường hợp không nhập
            {
                _ketthuc = "01-01-0001";
            }
            DateTime batdau = Convert.ToDateTime(_batdau);
            DateTime ketthuc = Convert.ToDateTime(_ketthuc);

            int total_rows = 1;
            var result = (from ks in datacontext.KhachSans
                          join d in datacontext.Deals on ks.MaKS equals d.KhachSan
                          join ctd in datacontext.ChiTietDatDeals on d.MaDeal equals ctd.MaDeal
                          join hd in datacontext.HoaDons on ctd.MaCT equals hd.CTDeal
                          where hd.NgayThanhToan >= batdau && hd.NgayThanhToan < ketthuc && hd.TinhTrang.Contains("Enabled") == true && ks.MaKS == khachsan
                          group new { ks, d, ctd, hd } by new { thang = System.Convert.ToDateTime(hd.NgayThanhToan).Month.ToString(), nam = System.Convert.ToDateTime(hd.NgayThanhToan).Year.ToString() } into kq
                          select new { thang = (kq.Key.thang + '-' + kq.Key.nam).ToString(), doanhthu = (float)kq.Sum(p => p.hd.TongTien) }).ToList();
            ViewBag.result = result;
            ViewBag.total_rows = total_rows;
            return Json(result);
        }
    }
}

Sources/HomeForYou/HomeForYou/Areas/back/Controllers/QuocGiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;


namespace HomeForYou.Areas.back.Controllers
{

    public class QuocGiaController : Controller
    {
        HelperController helper = new HelperController();
        string role;
        bool is_login;
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }
        // GET: /back/QuocGia/
        [HttpGet]
        public ActionResult Index()
        {
            return RedirectToAction("DanhSach");
        }

        public ActionResult DanhSachQuocGia(string title)
        {
            var dataContext = new HomeForYouDataContext();
            if (title != null)
            {
                List<QuocGia> quocgia = dataContext.QuocGias.Where(qgia => qgia.TenQG.Contains(title) == true).ToList();
                return View("DanhSachQuocGia", quocgia);
            }
            List<QuocGia> qg = dataContext.QuocGias.ToList();

            // kiem tra delete, edit
            foreach (var d in qg)
            {
                if (khong_xoa_sua(d.MaQG))
                {
                    d.Xoa = false;
                    d.Sua = false;
                }
            }
            return View("DanhSachQuocGia", qg);
        }

        public ActionResult ThemQuocGia()
        {

            return View();
        }
        [HttpPost]
        public ActionResult ThemQuocGia(string tenquocgia, string vung, HttpPostedFileBase hinhdaidien)
        {
            // manage role ko quan tam
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            QuocGia quocgia = new QuocGia();
            if (tenquocgia == "" || vung==""||vung==null||tenquocgia==null)
            {
                ViewBag.Message = "Vui lòng nhập đầy đủ thông tin bắt buộc.";
                ViewBag.Success = 0;
                return View();
            }
            quocgia.TenQG = tenquocgia;
            quocgia.Vung = vung;
            //xu ly hinh anh
            string fileName = Path.GetFileName(hinhdaidien.FileName);
            var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
            hinhdaidien.SaveAs(path);
            quocgia.HinhDaiDien = fileName;
            //ket thuc xu ly hinh
            quocgia.TinhTrang = "Enabled";
            quocgia.Xoa = true;
            quocgia.Sua = true;
            dataContext.QuocGias.InsertOnSubmit(quocgia);
            dataContext.SubmitChanges();
            ViewBag.Message = "Bạn đã thêm quốc gia " + tenquocgia + " thành công";
            ViewBag.Success = 1;
            return View();
        }

        [HttpGet]
        public ActionResult SuaQuocGia(int maqg)
        {
            // manage role ko quan tam
            if (!is_login)
              return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            
            var quocgias = (from s in dataContext.QuocGias
                            where s.MaQG == maqg
                            select s).Single();
            return View(quocgias);
        }

        [HttpPost]
        public ActionResult SuaQuocGia(int maqg, string tenquocgia, string vung, string tinhtrang, HttpPostedFileBase hinhdaidien)
        {
            // manage role ko quan tam
            if (!is_login)
               return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                            return View("../Helper/Access_Denied");
            // manage role ko quan tam
            var dataContext = new HomeForYouDataContext();
            var quocgia = (from s in dataContext.QuocGias
                           where s.MaQG == maqg
                           select s).Single();
            if (tenquocgia == null || tenquocgia == "" || vung == null || vung == "")
            {
                ViewBag.Error = "Vui lòng nhập đầy đủ thông tin bắt buộc!";
                return View(quocgia);
            }
            if (hinhdaidien != null)
            {
                //Xoa hinh truoc do
                char DirSeparator = System.IO.Path.DirectorySeparatorChar;
                string filepath = "Content/img" + DirSeparator + quocgia.HinhDaiDien;
                System.IO.File.Delete(Path.GetFullPath(AppDomain.CurrentDomain.BaseDirectory + filepath));
                //ket thuc xoa hinh
                //upload hinh anh
                string fileName = "";
                if (hinhdaidien.ContentLength > 0)
                {
                    fileName = Path.GetFileName(hinhdaidien.FileName);
                    var path = Path.Combine(Server.MapPath("~/Content/img"), fileName);
                    hinhdaidien.SaveAs(path);
                    quocgia.HinhDaiDien = hinhdaidien.FileName;
                }
                //ket thuc upload hinh
            }
            
            if (tenquocgia!="")
                quocgia.TenQG = tenquocgia;
            if (vung!="")
                quocgia.Vung = vung;
            quocgia.TinhTrang = tinhtrang;
            dataContext.SubmitChanges();
            ViewBag.Message = "Bạn cập nhật quốc gia " + tenquocgia + " thành công";
            return View(quocgia);
        }

        public bool khong_xoa_sua(int ID)
        {
            var dataContext = new HomeForYouDataContext();
            var ct = (from c in dataContext.ChiTietDatDeals
                      where c.Deal.KhachSan1.Vung1.ThanhPho1.QuocGia1.MaQG == ID
                      select c).Count();
            if (ct == 0)
            {
                return false; //cho phep xoa
            }
            return true;    //khong cho xoa
        }
        
        public void XoaQuocGia(int MaQG)
        {
            var dataContext = new HomeForYouDataContext();
            var quocgia = (from c in dataContext.QuocGias
                           where c.MaQG == MaQG
                           select c).Single();
            quocgia.TinhTrang = "Deleted";
            dataContext.SubmitChanges();
        }
       
    }
}

Sources/HomeForYou/HomeForYou/Areas/back/Views/QuocGia/BaoCao.cshtml
@using HomeForYou.Areas.back.Controllers;
@{
    ViewBag.Title = "ThongKeDoanhThu";
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}

<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    
</ul>
<h2>Báo cáo doanh thu</h2>

<p class="clearfix">
    <div class="pull-left container">
    <blockquote>
        <form class="form-horizontal" method="get" enctype="multipart/form-data">
            <div class="control-group">
                <label class="control-label">
                    Khách sạn: </label>
                <div class="control">
                    @Html.DropDownList("KhachSan","All")
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">
                    Từ ngày: </label>
                <div class="control">
                    <input type="text" name="batdau" id="start_date" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">
                    Đến ngày: </label>
                <div class="control">
                    <input type="text" name="ketthuc" id="end_date" />
                    <button type="submit" class="btn">
                    Tìm</button>
                </div>
            </div>
        </form>
    </blockquote>
    </div>
    <table class="table table-bordered table-striped table-center class">
        <thead>
            <tr>
                
                <th width="40%">
                    DoanhThu
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@ViewBag.total_rows == 0)
            {
                <tr>
                    <td colspan="5" class="align-center">
                        Không có kết quả phù hợp
                    </td>
                </tr>
            }
            @foreach (var s in @ViewBag.result)
            { 
                <tr>
                    
                    <td>
                        @s.doanhthu
                    </td>
               </tr>
            }
        </tbody>
    </table>
@*    <div class="pagination clearfix">
        @if ((string)ViewData["pageLinks"] != "")
        {
            <ul>
                @Html.Raw(ViewBag.pageLinks)
            </ul>
            <br />
            <br />
        }
    </div>*@

Sources/HomeForYou/HomeForYou/Areas/back/Views/QuocGia/DanhSachQuocGia.cshtml
@model IEnumerable<HomeForYou.QuocGia>
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}

<p class="clearfix">
 @Html.ActionLink("Thêm mới", "ThemQuocGia", "QuocGia", new { @class = "btn btn-primary pull-right" })
</p>
<div class="pull-left">
        <form class="form-search" method="get">
        <input type="text" class="input-medium search-query" name="title" placeholder="Từ khóa"
            value="" />
        <button type="submit" class="btn btn-success">
            Tìm</button>
        </form>
    </div>
<table class="table table-bordered table-striped table-center class">
    <thead>
        <tr>
            <th width="15%">Mã Quốc Gia
            </th>
            <th width="25%">Tên Quốc Gia
            </th>
            <th width="20%">Vùng
            </th>
            <th width="20%">Tình trạng
            </th>
            <th width="10%"></th>
            <th width="10%"></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var s in Model)
        { 
            <tr>
                <td style="text-align: center;">
                    @s.MaQG
                </td>
                <td style="text-align: center;">
                    @s.TenQG
                </td>
                <td style="text-align: center;">
                    @s.Vung
                </td>
                <td style="text-align: center;">
                    @s.TinhTrang
                </td>
                <td>
                        @if (s.Sua == true)
                        {
                            @Html.ActionLink("Sửa", "SuaQuocGia", "QuocGia", new {MaQG = s.MaQG }, new { @class = "btn btn-small" })
                        }
                        else
                        {
                            <button class="btn btn-small" disabled>
                                Sửa</button>
                        }
                    </td>
                    <td>
                        @if (s.Xoa == true && s.TinhTrang!="Deleted")
                        {
                            @Html.ActionLink("Xóa", "XoaQuocGia", "QuocGia", new { MaQG = s.MaQG }, new { @class = "btn btn-small btn-danger delete-row" })
                        }
                        else
                        {
                            <button class="btn btn-small btn-danger delete-row" disabled>
                                Xóa</button>
                        }
                    </td>
            </tr>
            }
    </tbody>
</table>

Sources/HomeForYou/HomeForYou/Areas/back/Views/QuocGia/Index.cshtml
@model IEnumerable<HomeForYou.NhanVien>
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}

Sources/HomeForYou/HomeForYou/Areas/back/Views/QuocGia/SuaQuocGia.cshtml
@model HomeForYou.QuocGia
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
@section scripts
{
    <script type="text/javascript">
    function SendToUrl() {
            window.location = '../DanhSach'
        }
    </script>
    
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách Quốc gia", "DanhSachQuocGia", "QuocGia") <span class="divider">/</span>
    </li>
    <li class="active">Cập nhật <span class="divider">/</span> </li>
    <li class="active"></li>
</ul>
<legend>Cập nhật quốc gia: </legend>
@if (@ViewBag.Message != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Chúc mừng!</h4>
        @ViewBag.Message
    </div>
}
@if (@ViewBag.Error != null)
{
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">x</button>   
    <h4>Lỗi!</h4>
    @ViewBag.Message
    </div>
}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
<div class="control-group">
    <label class="control-label">
       Mã Quốc Gia</label>
    <div class="controls">
        <input type="text" name="maqg" disabled value="@Model.MaQG"/>

    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Tên quốc gia</label>
    <div class="controls">
        <input type="text" name="tenquocgia" value="@Model.TenQG"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
       Vùng</label>
    <div class="controls">
        <input type="text" name="vung" value="@Model.Vung"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<legend>Tình trạng</legend>
<div class="control-group">
    <div class="controls">
        <select name="tinhtrang">
            <option value="Enabled"  @if (@Model.TinhTrang == "Enabled") { ViewContext.Writer.Write("selected"); }>
                Enabled</option>
            <option value="Disabled" @if (@Model.TinhTrang == "Disabled") { ViewContext.Writer.Write("selected"); }>
                Disabled</option>
            <option value="Deleted" @if (@Model.TinhTrang == "Deleted") { ViewContext.Writer.Write("selected"); }>
                Deleted</option>
        </select>
    </div>
</div>
<legend>Hình đại diện</legend>
<div class="control-group">
    <div class="controls">
        <input type="file" value="@Model.HinhDaiDien" name="hinhdaidien" id="hinhdaidien" />
        <img src="/Content/img/@Model.HinhDaiDien" id="pic1" name="pic1" alt="" align="middle" style="padding-top: 10px;" class="img-rounded"/>
    </div>
 </div>
 <legend></legend>
<p><strong style="color: Red;"> (*) </strong>
    <strong style="font-style:italic;">: Thông tin không được để trống</strong>
</p>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">
        Cập nhật</button>
    @Html.ActionLink("Thoát", "DanhSachQuocGia", "QuocGia", new { @class = "btn btn-inverse" })
</div>
</form>

Sources/HomeForYou/HomeForYou/Areas/back/Views/QuocGia/ThemQuocGia.cshtml
@model IEnumerable<HomeForYou.QuocGia>
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}

<ul class="breadcrumb">
        <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách quốc gia", "DanhSachQuocGia", "QuocGia") <span class="divider">/</span>
    </li>
    <li class="active">Thêm mới</li>
</ul>
<legend>Thêm quốc gia</legend>
@if (@ViewBag.Message != null && ViewBag.Success==1)
{
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4> Chúc mừng!</h4>
    @ViewBag.Message
</div>
}
@if (@ViewBag.Message != null && ViewBag.Success == 0)
{
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4> Không thành công!</h4>
    @ViewBag.Message
</div>
}
<form class="form-horizontal" action="ThemQuocGia" method="post" enctype="multipart/form-data">
<div class="control-group">
    <label class="control-label">
        Tên quốc gia</label>
    <div class="controls">
        <input type="text" name="tenquocgia" value=""/><span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Vùng</label>
    <div class="controls">
        <input type="text" name="vung" value=""/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Hình đại diện</label>
    <div class="controls">
        <input type="file" value="" name="hinhdaidien" id="hinhdaidien"/>
    </div>
</div>
<legend></legend>
<p><strong style="color: Red;"> (*) </strong><strong style="font-style:italic;">: Thông tin bắt buộc</strong></p>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">
        Thêm
    </button>
@Html.ActionLink("Thoát", "DanhSachQuocGia", "QuocGia", new { @class = "btn btn-inverse" })
</div>

</form>