Sources/HomeForYou/HomeForYou/Areas/back/Controllers/DealKSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace HomeForYou.Areas.back.Controllers
{
    public class DealKSController : Controller
    {
        //
        // GET: /back/Deal/
        HelperController helper = new HelperController();
        string role;
		int ma_nv;
        bool is_login;
		public class LichSuDeal
        {
            public ChiTietDatDeal ct_deal;
            public KhachHang khachhang;
        }
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            base.OnActionExecuting(ctx);
            if (ctx.HttpContext.Session["Role"] != null)
            {
                role = ctx.HttpContext.Session["Role"].ToString();
                is_login = (bool)ctx.HttpContext.Session["IsLogin"];
				ma_nv = (int)Session["Staff_ID"];
            }
            //role = ControllerContext.HttpContext.Session["Role"].ToString();
        }

        public void Index()
        {
            Response.Redirect("DanhSach");
        }

        public ActionResult DanhSach(int? country=null, int? city=null, int? area=null, int? hotel = null, int? month = null)
        {
            // manage role ko quan tam
            /*    if (HttpContext.Session == null || HttpContext.Session["IsLogin"] == null || HttpContext.Session["Role"] == null)
                    return RedirectToAction("Login", "Admin");*/
            if (!is_login)
                return RedirectToAction("Login", "Admin");
            if (!helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role))
                return View("../Helper/Access_Denied");
            // manage role ko quan tam
            ViewBag.TimeNow = DateTime.Now.Date.ToString("d/MM/yyyy");
            var dataContext = new HomeForYouDataContext();
            int total_rows = 0;
            if (hotel != null && month != null)
            {
                total_rows = (from d in dataContext.Deals
                                join km in dataContext.KhuyenMais on d.KhuyenMai equals km.MaKM
                                where (d.NgayBatDau.Value.Month == month || d.NgayKetThuc.Value.Month == month) && d.KhachSan == hotel
                                select d).Count();
            }
            total_rows = (from d in dataContext.Deals
                              join km in dataContext.KhuyenMais on d.KhuyenMai equals km.MaKM
                              select d).Count();
            ViewBag.total_rows = total_rows;
            string base_URL = "danhsach"; //quan trong, ten action cua controller

            //phan trang ko quan tam
            string URL_segment;
            try
            {
                URL_segment = Request.Url.Segments[4];
            }
            catch (Exception)
            {
                URL_segment = null;
            }
            Libraries.Pagination pagination = new Libraries.Pagination(base_URL, URL_segment, total_rows);
            string pageLinks = pagination.GetPageLinks();
            int start = (pagination.CurPage - 1) * pagination.PerPage;
            int offset = pagination.PerPage;
            if (URL_segment != null)
                pageLinks = pageLinks.Replace(base_URL + "/", "");
            ViewBag.pageLinks = pageLinks;
            //phan trang ko quan tam
            if (hotel != null && month != null && hotel!=0 && month!=0)//tim theo khach san va thang
            {
                var deals = (from d in dataContext.Deals
                             join km in dataContext.KhuyenMais on d.KhuyenMai equals km.MaKM
                             where (d.NgayBatDau.Value.Month == month || d.NgayKetThuc.Value.Month == month) && d.KhachSan == hotel
                             select d).Skip(start).Take(offset);
                // kiem tra delete, edit
                foreach (var d in deals)
                {
                    if (khong_xoa_sua(d))
                    {
                        d.Xoa = false;
                        d.Sua = false;
                    }
                }
                var countries = (from c in dataContext.QuocGias
                                 select c);
                ViewBag.Countries = countries;
                return View(deals);

            }
            var deal = (from d in dataContext.Deals
                     join km in dataContext.KhuyenMais on d.KhuyenMai equals km.MaKM
                     where ((country!=0 && country!=null && d.KhachSan1.Vung1.ThanhPho1.QuocGia1.MaQG==country)||(country==0 || country==null))
                           && ((city != 0 && city != null && d.KhachSan1.Vung1.ThanhPho1.MaTP == city) || (city==0 || city==null))
                           && ((area != 0 && area != null && d.KhachSan1.Vung1.MaVung == area) || (area==0 || area==null))
                     select d).Skip(start).Take(offset);
            // kiem tra delete, edit
            foreach (var d in deal)
            {
                if (khong_xoa_sua(d))
                {
                    d.Xoa = false;
                    d.Sua = false;
                }
            }
            var countrie = (from c in dataContext.QuocGias
                             select c);
            ViewBag.Countries = countrie;
            if (hotel != null && hotel!=0)
                ViewBag.hotel = dataContext.KhachSans.Where(ks => ks.MaKS == hotel).Single().TenKS.ToString();
            else
                ViewBag.hotel = "";
            if (country != null && country != 0)
                ViewBag.country = dataContext.QuocGias.Where(qg => qg.MaQG == country).Single().TenQG.ToString();
            else
                ViewBag.country = "";
            if (city != null && city!=0)
                ViewBag.city = dataContext.ThanhPhos.Where(tp => tp.MaTP == city).Single().TenTP.ToString();
            else
                ViewBag.city = "";
            if (area != null && area!=0)
                ViewBag.area = dataContext.Vungs.Where(v => v.MaVung == area).Single().TenVung.ToString();
            else
                ViewBag.area = "";
            return View(deal);
        }
		
		[HttpGet]
        public ActionResult Sua(int MaDeal)
        {
            var dataContext = new HomeForYouDataContext();
            var deal = (from d in dataContext.Deals
                        where d.MaDeal == MaDeal
                        select d).Single();
            var khuyenmai = (from k in dataContext.KhuyenMais
                             select k);
            var phong = (from p in dataContext.Phongs
                         select p);
            ViewBag.KhuyenMai = khuyenmai;
            ViewBag.Phong = phong;
            return View(deal);
        }
        [HttpPost]
        public ActionResult Sua(int MaDeal, float Gia, float Tien_Cong_Them, int Phong, DateTime NgayBD, DateTime NgayKT, int KhuyenMai, string tinhtrang)
        {
            // manage role ko quan tam
            if (HttpContext.Session == null || HttpContext.Session["IsLogin"] == null || HttpContext.Session["Role"] == null)
                return RedirectToAction("Login", "Admin");
            helper.Permission(ControllerContext.RouteData.Values["controller"].ToString(), ControllerContext.RouteData.Values["action"].ToString(), role);
            // manage role ko quan tam

            var dataContext = new HomeForYouDataContext();
            var deal = (from d in dataContext.Deals
                        where d.MaDeal == MaDeal
                        select d).Single();
            if (Gia == null || NgayBD == null || NgayKT == null)
            {
                ViewBag.Error = "Vui lòng nhập đầy đủ thông tin bắt buộc.";
                return View(deal);
            }
            deal.TienCongThem = Tien_Cong_Them;
            deal.Phong = Phong;
            deal.NgayBatDau = NgayBD;
            deal.NgayKetThuc = NgayKT;
            deal.KhuyenMai = KhuyenMai;
            deal.TinhTrang = tinhtrang;
            dataContext.SubmitChanges();

            var khuyenmai = (from k in dataContext.KhuyenMais
                             select k);
            var phong = (from p in dataContext.Phongs
                         select p);
            ViewBag.KhuyenMai = khuyenmai;
            ViewBag.Phong = phong;
            ViewBag.Message = "Bạn cập nhật deal thành công";
            return View(deal);
        }
        public ActionResult ChiTiet(int MaDeal, int? huy=null, int? tt = null)
        {
            var dataContext = new HomeForYouDataContext();
            var deal = (from d in dataContext.Deals
                        where d.MaDeal == MaDeal
                        select d).Single();
            var ls_deal = (from ctd in dataContext.ChiTietDatDeals
                           where ctd.MaDeal == MaDeal
                           select ctd);
            List<LichSuDeal> ct_deal_list = new List<LichSuDeal>();
            foreach (var l in ls_deal)
            {
                LichSuDeal lsd = new LichSuDeal();
                lsd.ct_deal = l; 
                var kh = (from k in dataContext.KhachHangs
                          where k.ID == l.MaKH
                          select k
                          ).Single();
                lsd.khachhang = kh;
                ct_deal_list.Add(lsd);
            }
            ViewBag.LichSuDatDeal = ct_deal_list;
            if (huy == 1)
            {
                ViewBag.Message = "Hủy deal thành công.";
            }
            if (tt==1)
            {
                ViewBag.Message = "Thanh toán deal thành công.";
            }
            return View(deal);
        }

        [HttpGet]
        public ActionResult Them()
        {
            var dataContext = new HomeForYouDataContext();
            var khachsan = (from k in dataContext.KhachSans
                            select k);

Sources/HomeForYou/HomeForYou/Areas/back/Views/DealKS/ChiTiet.cshtml
@model  HomeForYou.Deal
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách deal", "DanhSach", "DealKS") <span class="divider">/</span>
    </li>
    <li class="active">Chi tiết<span class="divider">/</span> </li>
    <li class="active"></li>
</ul>
<legend>Chi tiết deal: </legend>
@if (@ViewBag.Message != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Chúc mừng!</h4>
        @ViewBag.Message
    </div>
}
<dl class="dl-horizontal">
    <dt>Mã deal</dt>
    <dd>@Model.MaDeal</dd>
    <dt>Giá</dt>
    <dd>@Model.Gia</dd>
    <dt>Tiền cộng thêm</dt>
    <dd>@Model.TienCongThem</dd>
    <dt>Khách sạn</dt>
    <dd>@Model.KhachSan1.TenKS</dd>
    <dt>Phòng</dt>
    <dd>@Model.Phong1.LoaiPhong</dd>
    <dt>Ngày bắt đầu</dt>
    <dd>@Model.NgayBatDau</dd>
    <dt>Ngày kết thúc</dt>
    <dd>@Model.NgayKetThuc</dd>
    <dt>Nhân viên tạo deal</dt>
    <dd>@Model.NhanVien.HoTenNV</dd>
    <dt>Khuyến mãi</dt>
    <dd>@Model.KhuyenMai1.TenKhuyenMai</dd>
    <dt>Tình trạng</dt>
    <dd>@Model.TinhTrang</dd>
</dl>
<legend>Lịch sử đặt Deal</legend>
<table class="table table-bordered table-striped table-center class">
    <thead>
        <tr>
            <th width="10%">
                Số thẻ KH
            </th>
            <th width="5%">
                Họ
            </th>
            <th width="5%">
                Tên
            </th>
            <th width="5%">
                Số phòng
            </th>
            <th width="10%">
                Ngày nhận
            </th>
            <th width="10%">
                Ngày trả
            </th>
            <th width="10%">
                Tình trạng
            </th>
            <th width="15%">
            </th>
            <th width="10%">
            </th>
        </tr>
    </thead>
    <tbody>
        @if (@ViewBag.total_rows == 0)
        {
            <tr>
                <td colspan="10" class="align-center">
                    Không có kết quả phù hợp
                </td>
            </tr>
        }
        @foreach (var d in @ViewBag.LichSuDatDeal)
        { 
            <tr>
                <td style="text-align: center;">
                    @d.ct_deal.MaKH
                </td>
                <td style="text-align: center;">
                    @d.khachhang.Ho
                </td>
                <td style="text-align: center;">
                    @d.khachhang.Ten
                </td>
                <td style="text-align: center;">
                    @d.ct_deal.SoPhong
                </td>
                <td style="text-align: center;">
                    @d.ct_deal.NgayNhan
                </td>
                <td style="text-align: center;">
                    @d.ct_deal.NgayTra
                </td>
                @{
               string tinh_trang = @d.ct_deal.TinhTrang;
                }
                @switch (tinh_trang)
                {
                    case "Unpaid":
                    <td>
                        <span class="label btn-primary">Unpaid</span>&nbsp;
                    </td>
                        break;
                    case "Deleted":
                    <td>
                        <span class="label btn-danger">Deleted</span>&nbsp;
                    </td>
                        break;
                    case "Paid":
                    <td>
                        <span class="label btn-primary">Paid</span>&nbsp;
                    </td>
                        break;
                }
                <td>
                    @if (tinh_trang == "Unpaid")
                    {
                        @Html.ActionLink("Thanh toán", "ThanhToanDeal", "DealKS", new { MaCT = d.ct_deal.MaCT, MaDeal =(int) d.ct_deal.MaDeal }, new { @class = "btn btn-info payment" })
                    }
                    else
                    {
                        <button class="btn btn-info" disabled>
                            Thanh toán</button>
                    }
                </td>
                <td>
                    @if (tinh_trang == "Unpaid")
                    {
                        @Html.ActionLink("Hủy", "HuyThanhToanDeal", "DealKS", new { MaCT = d.ct_deal.MaCT, MaDeal =(int) d.ct_deal.MaDeal }, new { @class = "btn btn-danger cancel-payment" })
                    }
                    else
                    {
                        <button class="btn btn-danger" disabled>
                            Hủy</button>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

Sources/HomeForYou/HomeForYou/Areas/back/Views/DealKS/DanhSach.cshtml
@model IEnumerable<HomeForYou.Deal>
@using HomeForYou.Areas.back.Controllers
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách deal", "DanhSach", "DealKS") <span class="divider"></span>
    </li>
</ul>
<p class="clearfix">
    @Html.ActionLink("Thêm mới", "Them", "Deal", new { @class = "btn btn-primary pull-right" })
    <div class="pull-left">
        <form class="form-search" method="get">
        <div class="container">
            <ul class="nav nav-pills filter pull-left">
                <li class="country-list">
                    <select id="country_list" name="country">
                        <option value="0">Quốc gia</option>
                        @foreach (var q in @ViewBag.Countries)
                        {
                            <option value="@q.MaQG" @if (HttpContext.Current.Request["country"] != null && q.MaQG == Int32.Parse(HttpContext.Current.Request["country"])) { ViewContext.Writer.Write("selected"); }>@q.TenQG</option>
                        }
                    </select>
                </li>
                <li class="city-list">
                    <select id="city_list" name="city">
                        @if (HttpContext.Current.Request["city"] != null && ViewBag.city!="")
                        {
                            @*<option value="@HttpContext.Current.Request["city"]">@Model.First().KhachSan1.Vung1.ThanhPho1.TenTP</option>*@
                            <option value="@HttpContext.Current.Request["city"]">@ViewBag.city</option>
                        }
                        else
                        {
                            <option value="0">Thành phố</option>
                        }
                    </select>
                </li>
                <li class="area-list">
                    <select id="area_list" name="area">
                        @if (HttpContext.Current.Request["area"] != null && ViewBag.area!="")
                        {
                            @*<option value="@HttpContext.Current.Request["area"]">@Model.First().KhachSan1.Vung1.TenVung</option>*@
                            <option value="@HttpContext.Current.Request["area"]">@ViewBag.area</option>
                        }
                        else
                        {
                            <option value="0">Vùng</option>
                        }
                    </select>
                </li>
            </ul>
            <ul class="nav nav-pills filter pull-left">
                <li class="hotel-list">
                    <select id="hotel_list" name="hotel">
                        @if (HttpContext.Current.Request["hotel"] != null && ViewBag.hotel!="")
                        {
                            @*<option value="@HttpContext.Current.Request["hotel"]">@Model.First().KhachSan1.TenKS</option>*@
                            <option value="@HttpContext.Current.Request["hotel"]">@ViewBag.hotel</option>
                        }
                        else
                        {
                            <option value="0">Khách sạn</option>
                        }
                    </select>
                </li>
                <li class="month-list">
                    <select id="month_list" name="month">
                        <option value="0">----- Tháng -----</option>
                        @{
                            var count = 1;
                        }
                        @while (count <= 12)
                        {
                            if (HttpContext.Current.Request["month"] != null && HttpContext.Current.Request["month"] == count.ToString())
                            {
                            <option value="@count" selected>Tháng @count</option>
                            }
                            else
                            {
                            <option value="@count">Tháng @count</option>
                            }
                            count++;
                        }
                    </select>
                </li>
                <li>
                    <button type="submit" class="btn btn-success">
                        Tìm</button>
                </li>
            </ul>
        </div>
        </form>
    </div>
    <table class="table table-bordered table-striped table-center class">
        <thead>
            <tr>
                <th width="5%">
                    Mã deal
                </th>
                <th width="10%">
                    Giá
                </th>
               <th width="25%">
                    Khách sạn
                </th>
                <th width="10%">
                    Ngày bắt đầu
                </th>
                <th width="10%">
                    Ngày hết hạn
                </th>
                <th width="10%">
                    Tình trạng
                </th>
				<th width="15%">
                </th>
                <th width="10%">
                </th>
                <th width="10%">
                </th>
            </tr>
        </thead>
        <tbody>
            @if (@ViewBag.total_rows == 0)
            {
                <tr>
                    <td colspan="10" class="align-center">
                        Không có kết quả phù hợp
                    </td>
                </tr>
            }
            @foreach (var d in Model)
            { 
                <tr>
                    <td style="text-align: center;">
                         @d.MaDeal
                    </td>
                    <td style="text-align: center;">
                        @d.Gia
                    </td>
                    <td style="text-align: center;">
                        @d.KhachSan1.TenKS
                    </td>
                    <td style="text-align: center;">
                        @d.NgayBatDau
                    </td>
                    <td style="text-align: center;">
                        @d.NgayKetThuc
                    </td>
                    @switch (d.TinhTrang)
                    {
                        case "Disabled":
                        <td>
                            <span class="label btn-warning">Disabled</span>&nbsp;
                        </td>
                            break;
                        case "Deleted":
                        <td>
                            <span class="label btn-danger">Deleted</span>&nbsp;
                        </td>
                            break;
                        default:
                        <td>
                            <span class="label btn-primary">Enabled</span>&nbsp;
                        </td>
                            break;
                    }	
					<td>
                            @Html.ActionLink("Chi tiết", "ChiTiet", "DealKS", new { MaDeal = d.MaDeal }, new { @class = "btn btn-info" })
                    </td>
                    <td>
                        @if (d.Sua == true)
                        {
                            @Html.ActionLink("Sửa", "Sua", "DealKS", new { MaDeal = d.MaDeal }, new { @class = "btn btn-small" })
                        }
                        else
                        {
                            <button class="btn btn-small" disabled>
                                Sửa</button>
                        }
                    </td>
                    <td>
                        @if (d.Xoa == true && d.TinhTrang != "Deleted")
                        {
                            @Html.ActionLink("Xóa", "Xoa", "DealKS", new { MaDeal = d.MaDeal }, new { @class = "btn btn-small btn-danger delete-row" })
                        }
                        else
                        {
                            <button class="btn btn-small btn-danger delete-row" disabled>
                                Xóa</button>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div class="pagination clearfix">
        @if ((string)ViewData["pageLinks"] != "")
        {
            <ul>
                @Html.Raw(ViewBag.pageLinks)
            </ul>
            <br />
            <br />
        }
    </div>

Sources/HomeForYou/HomeForYou/Areas/back/Views/DealKS/Sua.cshtml
@model  HomeForYou.Deal
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
    <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách deal", "DanhSach", "DealKS") <span class="divider">/</span>
    </li>
    <li class="active">Cập nhật <span class="divider">/</span> </li>
    <li class="active"></li>
</ul>
<legend>Cập nhật deal: </legend>
@if (@ViewBag.Message != null)
{
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Chúc mừng!</h4>
        @ViewBag.Message
    </div>
}
@if (@ViewBag.Error != null)
{
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">
            ×</button>
        <h4>
            Lỗi!</h4>
        @ViewBag.Error
    </div>
}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
<div class="control-group">
 <label class="control-label">
        Mã deal</label>
    <div class="controls">
        <input type="text" disabled name="MaDeal" value="@Model.MaDeal"/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Giá</label>
    <div class="controls">
        <input type="text" name="Gia" value="@Model.Gia"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Tiền cộng thêm</label>
    <div class="controls">
        <input type="text" name="Tien_Cong_Them" value="@Model.TienCongThem"/>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Khách sạn</label>
    <div class="controls">
        <input type="text" name="KS" disabled value="@Model.KhachSan1.TenKS"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Phòng</label>
    <div class="controls">
        <select name="Phong">
            @foreach (var p in ViewBag.Phong)
            {
                 <option value="@p.MaPhong"  @if (@Model.Phong == @p.MaPhong) { ViewContext.Writer.Write("selected"); }>
                @p.LoaiPhong</option>
            }
        </select>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Ngày bắt đầu</label>
    <div class="controls">
        <input type="text" id="start_date" name="NgayBD" value="@Model.NgayBatDau"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Ngày kết thúc</label>
    <div class="controls">
        <input type="text" id="end_date" name="NgayKT" value="@Model.NgayKetThuc"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Khuyến mãi</label>
    <div class="controls">
        <select name="KhuyenMai">
             @foreach (var k in ViewBag.KhuyenMai)
            {
                 <option value="@k.MaKM"  @if (@Model.KhuyenMai == @k.MaKM) { ViewContext.Writer.Write("selected"); }>
                @k.TenKhuyenMai</option>
            }
        </select>
    </div>
</div>
<legend>Status</legend>
<div class="control-group">
    <div class="controls">
        <select name="tinhtrang">
            <option value="Enabled"  @if (@Model.TinhTrang == "Enabled") { ViewContext.Writer.Write("selected"); }>
                Enabled</option>
            <option value="Disabled" @if (@Model.TinhTrang == "Disabled") { ViewContext.Writer.Write("selected"); }>
                Disabled</option>
            <option value="Deleted" @if (@Model.TinhTrang == "Deleted") { ViewContext.Writer.Write("selected"); }>
                Deleted</option>
        </select>
    </div>
</div>
<legend></legend>
<p><strong style="color: Red;"> (*) </strong>
    <strong style="font-style:italic;">: Thông tin không được để trống</strong>
</p>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">
        Cập nhật</button>
    @Html.ActionLink("Thoát", "DanhSach", "DealKS", new { @class = "btn btn-inverse" })
</div>
</form>

Sources/HomeForYou/HomeForYou/Areas/back/Views/DealKS/Them.cshtml
@{
    Layout = "~/Areas/back/Views/Shared/back_layout.cshtml";
}
<ul class="breadcrumb">
        <li>@Html.ActionLink("Trang chủ", "Index", "Admin")<span class="divider">/</span>
    </li>
    <li>@Html.ActionLink("Danh sách deal", "DanhSach", "DealKS") <span class="divider">/</span>
    </li>
    <li class="active">Thêm mới</li>
</ul>
<legend>Thêm deal</legend>
@if (@ViewBag.Message != null && ViewBag.Success==1)
{
<div class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4> Chúc mừng!</h4>
    @ViewBag.Message
</div>
}
@if (@ViewBag.Message != null&&ViewBag.Success==0)
{
<div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4> Không thành công!</h4>
    @ViewBag.Message
</div>
}

<form class="form-horizontal add-deal" action="Them" method="post" enctype="multipart/form-data">
<div class="control-group">
    <label class="control-label">
        Giá (Đơn vị tính: VNĐ)</label>
    <div class="controls">
        <input type="text" name="Gia" value="0"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Tiền cộng thêm (Đơn vị tính: VNĐ)</label>
    <div class="controls">
        <input type="text" name="Tien_Cong_Them" value="0"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Khách sạn</label>
    <div class="controls">
        <select name="KhachSan" id="khachsan_list">
          <option value="0">
                ---------- Khách Sạn ----------</option>
            @foreach (var p in ViewBag.KhachSan)
            {
                 <option value="@p.MaKS">
                @p.TenKS</option>
            }
        </select><span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Phòng</label>
    <div class="controls">
        <select name="Phong" id="phong_list">
        <option value="0">-------------Phòng---------------</option>
        </select>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Ngày bắt đầu</label>
    <div class="controls">
        <input type="text" id="start_date" name="NgayBD"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Ngày kết thúc</label>
    <div class="controls">
        <input type="text" id="end_date" name="NgayKT"/>
        <span class="help-inline" style="color: red;">(*)</span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">
        Khuyến mãi</label>
    <div class="controls">
        <select name="KhuyenMai">
             @foreach (var k in ViewBag.KhuyenMai)
            {
                 <option value="@k.MaKM">
                @k.TenKhuyenMai</option>
            }
        </select>
    </div>
</div>
<legend></legend>
<p><strong style="color: Red;"> (*) </strong><strong style="font-style:italic;">: Thông tin bắt buộc</strong></p>
<div class="form-actions">
    <button type="submit" class="btn btn-primary">
        Thêm
    </button>
    @Html.ActionLink("Thoát", "DanhSach", "DealKS", new { @class = "btn btn-inverse" })
</div>
</form>